### ISSUE TITLE
Odd Errors won't pass test

### ISSUE THREAD

**Issue by cedric-joaquin** [learn-co-curriculum/fewpjs-stitching-together-the-three-pillars-new#4]
1) "after all" hook in "{root}"

/Users/cedricjoaquin/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/strategies/mocha.rb:42:in `results': undefined method `[]' for nil:NilClass (NoMethodError)

We've commented out the tests in `test/indexTest.js` and we still get the error shown above. Had to just move on with test not passing.

**Comment by lizbur10** [comment]
Hello! This particular error is often due to a versioning conflict between the lab's dependencies and something in your local environment. It doesn't appear that other students are encountering the same problem so I'm going to go ahead and close this issue.

Apologies for the inconvenience and thanks for contributing to the Flatiron curriculum 💙
